# Generated by Django 5.2.14 on 2026-05-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_membership_joined_at_alter_membership_role'),
        ('projects', '0002_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('organization', 'slug')},
        ),
    ]
